# Generated by Django 5.1.4 on 2025-01-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Item_name",
            field=models.CharField(max_length=40),
        ),
    ]
