# Generated by Django 5.1.4 on 2025-01-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_App", "0002_alter_item_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Image",
            field=models.ImageField(blank=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="Image",
            field=models.ImageField(upload_to="items/"),
        ),
    ]
